apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: headroom-gateway
  labels:
    app: headroom-gateway
spec:
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: headroom-gateway
  port:
    targetPort: http
